### ISSUE TITLE
linux-intel-iot-lts-5.15-5.15++gitAUTOINC+4c1d7cd3a9_36cef9f063-r0 do_fetch: Failed to fetch URL git:///home/avalue/20230222-yocot_work/build/../managed/linux-intel-iot-lts-5.15;name=machine;branch=HEAD;nobranch=1;protocol=file;usehead=1,

### ISSUE THREAD

**Issue by ginochen-avalue** [intel/iotg-yocto-ese-manifest#12]
Hi 
I use ubuntu 20.04 to build the yocto image according to 641840_Yocto_Project_ BSP_12_Gen_Intel_Core_GSG_Rev1.3.pdf.
When we run "bitbake mc:x86-2021:core-image-sato-sdk" this command, but I got following in error message.
Could you please check it for me? Thanks.

=================================================================================
WARNING: mc:x86-2021:linux-intel-iot-lts-5.15-5.15++gitAUTOINC+4c1d7cd3a9_36cef9f063-r0 do_fetch: Failed to fetch URL git:///home/avalue/20230222-yocot_work/build/../managed/linux-intel-iot-lts-5.15;name=machine;branch=HEAD;nobranch=1;protocol=file;usehead=1, attempting MIRRORS if available
ERROR: mc:x86-2021:linux-intel-iot-lts-5.15-5.15++gitAUTOINC+4c1d7cd3a9_36cef9f063-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export PATH="/home/avalue/20230222-yocot_work/build/tmp-x86-2021-glibc/work/intel_corei7_64-ese-linux/linux-intel-iot-lts-5.15/5.15++gitAUTOINC+4c1d7cd3a9_36cef9f063-r0/recipe-sysroot-native/usr/bin/python3-native:/home/avalue/20230222-yocot_work/intel-embedded-system-enabling/scripts:/home/avalue/20230222-yocot_work/build/tmp-x86-2021-glibc/work/intel_corei7_64-ese-linux/linux-intel-iot-lts-5.15/5.15++gitAUTOINC+4c1d7cd3a9_36cef9f063-r0/recipe-sysroot-native/usr/bin/x86_64-ese-linux:/home/avalue/20230222-yocot_work/build/tmp-x86-2021-glibc/work/intel_corei7_64-ese-linux/linux-intel-iot-lts-5.15/5.15++gitAUTOINC+4c1d7cd3a9_36cef9f063-r0/recipe-sysroot/usr/bin/crossscripts:/home/avalue/20230222-yocot_work/build/tmp-x86-2021-glibc/work/intel_corei7_64-ese-linux/linux-intel-iot-lts-5.15/5.15++gitAUTOINC+4c1d7cd3a9_36cef9f063-r0/recipe-sysroot-native/usr/sbin:/home/avalue/20230222-yocot_work/build/tmp-x86-2021-glibc/work/intel_corei7_64-ese-linux/linux-intel-iot-lts-5.15/5.15++gitAUTOINC+4c1d7cd3a9_36cef9f063-r0/recipe-sysroot-native/usr/bin:/home/avalue/20230222-yocot_work/build/tmp-x86-2021-glibc/work/intel_corei7_64-ese-linux/linux-intel-iot-lts-5.15/5.15++gitAUTOINC+4c1d7cd3a9_36cef9f063-r0/recipe-sysroot-native/sbin:/home/avalue/20230222-yocot_work/build/tmp-x86-2021-glibc/work/intel_corei7_64-ese-linux/linux-intel-iot-lts-5.15/5.15++gitAUTOINC+4c1d7cd3a9_36cef9f063-r0/recipe-sysroot-native/bin:/home/avalue/20230222-yocot_work/intel-embedded-system-enabling/bitbake/bin:/home/avalue/20230222-yocot_work/build/tmp-x86-2021-glibc/hosttools"; export HOME="/home/avalue"; LANG=C git -c core.fsyncobjectfiles=0 -c gc.autoDetach=false -c core.pager=cat clone --bare --mirror /home/avalue/20230222-yocot_work/build/../managed/linux-intel-iot-lts-5.15 /home/avalue/20230222-yocot_work/build/downloads/git2/home.avalue.20230222-yocot_work.build....managed.linux-intel-iot-lts-5.15 --progress failed with exit code 128, no output
ERROR: mc:x86-2021:linux-intel-iot-lts-5.15-5.15++gitAUTOINC+4c1d7cd3a9_36cef9f063-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git:///home/avalue/20230222-yocot_work/build/../managed/linux-intel-iot-lts-5.15;name=machine;branch=HEAD;nobranch=1;protocol=file;usehead=1')
ERROR: Logfile of failure stored in: /home/avalue/20230222-yocot_work/build/tmp-x86-2021-glibc/work/intel_corei7_64-ese-linux/linux-intel-iot-lts-5.15/5.15++gitAUTOINC+4c1d7cd3a9_36cef9f063-r0/temp/log.do_fetch.156256
ERROR: Task (mc:x86-2021:/home/avalue/20230222-yocot_work/build/../intel-embedded-system-enabling/meta-intel-embedded-system-enabling/meta-intel-iot-bsp/recipes-kernel/linux/linux-intel-iot-lts-5.15_git.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1293 tasks of which 1236 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  mc:x86-2021:/home/avalue/20230222-yocot_work/build/../intel-embedded-system-enabling/meta-intel-embedded-system-enabling/meta-intel-iot-bsp/recipes-kernel/linux/linux-intel-iot-lts-5.15_git.bb:do_fetch
Summary: There were 24 WARNING messages.
Summary: There were 2 ERROR messages, returning a non-zero exit code.

**Comment by ginochen-avalue** [comment]
Could someone help?

**Comment by Harvey-Tsai** [comment]
I have the same issue.

**Comment by arunimaaaa** [comment]
I'm facing the same issue as well. Is there a resolution to this?

**Comment by fankunyang** [comment]
Yes, I am having this issue, too.

**Comment by simplelalu** [comment]
I have the same issue.

**Comment by arunimaaaa** [comment]
Hi All,
I had spoken to Preeti Sachan, who is the owner of this github repo, she suggested me the below suggestions. Firstly, update the git to 2.35.0 version. If only upgdating git doesn't work, try the below options. Option 2 worked for me. If you have further queries, I'd suggest you to connect with her.

Option 1
try this zenith@nation-z:~/work/disk-b/yocto/adl-s/mr3/intel-embedded-system-enabling/bitbake$ git diff
diff --git a/lib/bb/fetch2/git.py b/lib/bb/fetch2/git.py
index f0df6fb6..8b25279a 100644
--- a/lib/bb/fetch2/git.py
+++ b/lib/bb/fetch2/git.py
@@ -362,6 +362,8 @@ class Git(FetchMethod):
            if repourl.startswith(file://):
                repourl = repourl[7:]
            clone_cmd = "LANG=C %s clone --bare --mirror %s %s --progress" % (ud.basecmd, shlex.quote(repourl), ud.clonedir)
+            if not ud.noshared:
+                clone_cmd += " -s"
            if ud.proto.lower() != 'file':
                bb.fetch2.check_network_access(d, clone_cmd, ud.url)
            progresshandler = GitProgressHandler(d

Option 2
 /managed/linux-intel-iot-lts-rt-5.15/.git/objects as a symlink causing the build issue.
 
 After creating non-symlink objects, this issue is gone.
============================================
cd ~/Yocto/ehl_mr6/managed/linux-intel-iot-lts-rt-5.15/.git
mv objects objects_bk && mkdir objects && cp -R objects_bk/* objects
 
cd ~/Yocto/ehl_mr6/managed/yocto-kernel-cache-5.15/.git/
mv objects objects_bk && mkdir objects && cp -R objects_bk/* objects
 
cd ~/Yocto/ehl_mr6/managed/linux-intel-iot-lts-5.15/.git
mv objects objects_bk && mkdir objects && cp -R objects_bk/* objects
============================================

**Comment by ginochen-avalue** [comment]
Hi All

After add Option1, the BSP can be compiled successfully in Ubuntu 20.04.
My issue has been resolved.  Thank you very much for your assistance.

Change the git.py file located /intel-embedded-system-enabling/bitbake/lib/bb/fetch2 folder.
At line 359, add "if not ud.noshared:" and "clone_cmd += “ -s”."

```
           if repourl.startswith("file://"):
               repourl = repourl[7:]
           clone_cmd = "LANG=C %s clone --bare --mirror %s %s --progress" % (ud.basecmd, shlex.quote(repourl), ud.clonedir)
           if not ud.noshared:
               clone_cmd += " -s"
           if ud.proto.lower() != 'file':
               bb.fetch2.check_network_access(d, clone_cmd, ud.url)
           progresshandler = GitProgressHandler(d)
           runfetchcmd(clone_cmd, d, log=progresshandler)
```

**Comment by simplelalu** [comment]
Dear all 
I used option 1 and successfully build the yocto image
thanks 

Option 1
try this zenith@nation-z:~/work/disk-b/yocto/adl-s/mr3/intel-embedded-system-enabling/bitbake$ git diff
diff --git a/lib/bb/fetch2/git.py b/lib/bb/fetch2/git.py
index f0df6fb6..8b25279a 100644
--- a/lib/bb/fetch2/git.py
+++ b/lib/bb/fetch2/git.py
@@ -362,6 +362,8 @@ class Git(FetchMethod):
if repourl.startswith(file://):
repourl = repourl[7:]
clone_cmd = "LANG=C %s clone --bare --mirror %s %s --progress" % (ud.basecmd, shlex.quote(repourl), ud.clonedir)

       if not ud.noshared:
           clone_cmd += " -s"
      if ud.proto.lower() != 'file':
          bb.fetch2.check_network_access(d, clone_cmd, ud.url)
      progresshandler = GitProgressHandler(d
