### ISSUE TITLE
lxc-4.0.1-r0 do_fetch: Failed to fetch URL http://linuxcontainers.org/downloads/lxc-4.0.1.tar.gz

### ISSUE THREAD

**Issue by fengyingchu0827** [intel/iotg-yocto-ese-manifest#3]
Hi,
I use ubuntu18.04 to build the yocto image according to your instruction. But I got the fail of do_fetch on lxc-4.0.1-r0. I found the log shows "Failed to fetch URL http://linuxcontainers.org/downloads/lxc-4.0.1.tar.gz, attempting MIRRORS if available", and I try to open that link and it doesn't work.

However, I try to open the link: https://linuxcontainers.org/downloads/lxc/lxc-4.0.1.tar.gz by the Browser, and It is workable.
I think there is something wrong with your codes. Could you please check it for me? Thanks.

==================================================================
Log:
NOTE: Running task 1176 of 11811 (mc:x86:/home/fengying_chu/workspace/tsn/release-58/build/../intel-embedded-system-enabling/meta-virtualization/recipes-containers/lxc/lxc_4.0.1.bb:do_fetch)
NOTE: recipe dtc-1.6.0-r0: task do_fetch: Started
NOTE: Running task 1177 of 11811 (mc:x86:/home/fengying_chu/workspace/tsn/release-58/build/../intel-embedded-system-enabling/meta/recipes-extended/parted/parted_3.3.bb:do_fetch)
NOTE: Running task 1178 of 11811 (mc:x86:/home/fengying_chu/workspace/tsn/release-58/build/../intel-embedded-system-enabling/meta/recipes-devtools/qemu/qemu_4.2.0.bb:do_fetch)
NOTE: recipe lxc-4.0.1-r0: task do_fetch: Started
NOTE: recipe libsdl2-2.0.12-r0: task do_fetch: Succeeded
NOTE: recipe linux-intel-ese-lts-rt-5.4-5.4++gitAUTOINC+4fa886b20f_db8c85db08-r0: task do_unpack: Started
NOTE: Running task 1179 of 11811 (mc:x86:/home/fengying_chu/workspace/tsn/release-58/build/../intel-embedded-system-enabling/meta/recipes-graphics/xorg-lib/libxft_2.3.3.bb:do_unpack)
NOTE: recipe parted-3.3-r0: task do_fetch: Started
NOTE: recipe qemu-4.2.0-r0: task do_fetch: Started
NOTE: Running task 1180 of 11811 (mc:x86:/home/fengying_chu/workspace/tsn/release-58/build/../intel-embedded-system-enabling/meta/recipes-support/fribidi/fribidi_1.0.9.bb:do_unpack)
WARNING: mc:x86:lxc-4.0.1-r0 do_fetch: Failed to fetch URL http://linuxcontainers.org/downloads/lxc-4.0.1.tar.gz, attempting MIRRORS if available
NOTE: recipe libxft-1_2.3.3-r0: task do_unpack: Started
NOTE: recipe fribidi-1.0.9-r0: task do_unpack: Started
NOTE: recipe qemu-4.2.0-r0: task do_fetch: Succeeded
NOTE: Running task 1181 of 11811 (mc:x86:/home/fengying_chu/workspace/tsn/release-58/build/../intel-embedded-system-enabling/meta/recipes-support/fribidi/fribidi_1.0.9.bb:do_write_config)
ERROR: mc:x86:lxc-4.0.1-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; unset _PYTHON_SYSCONFIGDATA_NAME; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export PATH="/home/fengying_chu/workspace/tsn/release-58/build/tmp-x86-glibc/work/corei7-64-ese-linux/lxc/4.0.1-r0/recipe-sysroot-native/usr/bin/python3-native:/home/fengying_chu/workspace/tsn/release-58/intel-embedded-system-enabling/scripts:/home/fengying_chu/workspace/tsn/release-58/build/tmp-x86-glibc/work/corei7-64-ese-linux/lxc/4.0.1-r0/recipe-sysroot-native/usr/bin/x86_64-ese-linux:/home/fengying_chu/workspace/tsn/release-58/build/tmp-x86-glibc/work/corei7-64-ese-linux/lxc/4.0.1-r0/recipe-sysroot/usr/bin/crossscripts:/home/fengying_chu/workspace/tsn/release-58/build/tmp-x86-glibc/work/corei7-64-ese-linux/lxc/4.0.1-r0/recipe-sysroot-native/usr/sbin:/home/fengying_chu/workspace/tsn/release-58/build/tmp-x86-glibc/work/corei7-64-ese-linux/lxc/4.0.1-r0/recipe-sysroot-native/usr/bin:/home/fengying_chu/workspace/tsn/release-58/build/tmp-x86-glibc/work/corei7-64-ese-linux/lxc/4.0.1-r0/recipe-sysroot-native/sbin:/home/fengying_chu/workspace/tsn/release-58/build/tmp-x86-glibc/work/corei7-64-ese-linux/lxc/4.0.1-r0/recipe-sysroot-native/bin:/home/fengying_chu/workspace/tsn/release-58/intel-embedded-system-enabling/bitbake/bin:/home/fengying_chu/workspace/tsn/release-58/build/tmp-x86-glibc/hosttools"; export HOME="/home/fengying_chu"; /usr/bin/env wget -t 2 -T 30 --passive-ftp --no-check-certificate -P /home/fengying_chu/workspace/tsn/release-58/build/downloads 'http://linuxcontainers.org/downloads/lxc-4.0.1.tar.gz' --progress=dot -v failed with exit code 8, output:
--2021-03-11 06:46:05--  http://linuxcontainers.org/downloads/lxc-4.0.1.tar.gz
Resolving linuxcontainers.org (linuxcontainers.org)... 170.39.196.167, 2602:fd23:8:1::8
Connecting to linuxcontainers.org (linuxcontainers.org)|170.39.196.167|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://linuxcontainers.org/downloads/lxc-4.0.1.tar.gz [following]
--2021-03-11 06:46:06--  https://linuxcontainers.org/downloads/lxc-4.0.1.tar.gz
Connecting to linuxcontainers.org (linuxcontainers.org)|170.39.196.167|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-11 06:46:07 ERROR 404: Not Found.

ERROR: mc:x86:lxc-4.0.1-r0 do_fetch: Fetcher failure for URL: 'http://linuxcontainers.org/downloads/lxc-4.0.1.tar.gz'. Unable to fetch URL from any source.
NOTE: recipe fribidi-1.0.9-r0: task do_write_config: Started
ERROR: Logfile of failure stored in: /home/fengying_chu/workspace/tsn/release-58/build/tmp-x86-glibc/work/corei7-64-ese-linux/lxc/4.0.1-r0/temp/log.do_fetch.23162
NOTE: recipe lxc-4.0.1-r0: task do_fetch: Failed
ERROR: Task (mc:x86:/home/fengying_chu/workspace/tsn/release-58/build/../intel-embedded-system-enabling/meta-virtualization/recipes-containers/lxc/lxc_4.0.1.bb:do_fetch) failed with exit code '1'
NOTE: recipe fribidi-1.0.9-r0: task do_write_config: Succeeded
NOTE: recipe libxft-1_2.3.3-r0: task do_unpack: Succeeded
NOTE: recipe pulseaudio-13.0-r0: task do_fetch: Succeeded
NOTE: recipe parted-3.3-r0: task do_fetch: Succeeded
NOTE: recipe dtc-1.6.0-r0: task do_fetch: Succeeded
NOTE: recipe icu-native-66.1-r0: task do_populate_sysroot: Succeeded
NOTE: recipe fribidi-1.0.9-r0: task do_unpack: Succeeded
NOTE: recipe linux-intel-ese-lts-5.4-5.4++gitAUTOINC+4fa886b20f_17d8b8b5ea-r0: task do_unpack: Succeeded
NOTE: recipe binutils-native-2.34-r0: task do_install: Succeeded
NOTE: recipe python3-native-3.8.2-r0: task do_install: Succeeded
NOTE: recipe linux-intel-ese-lts-rt-5.4-5.4++gitAUTOINC+4fa886b20f_db8c85db08-r0: task do_unpack: Succeeded
NOTE: recipe gstreamer1.0-1.19.0.1-r0: task do_fetch: Succeeded
NOTE: recipe cmake-native-3.16.5-r0: task do_configure: Succeeded
NOTE: recipe gcc-cross-x86_64-9.3.0-r0: task do_compile: Succeeded
NOTE: recipe llvm-project-source-10.0.1-10.0.1-r0: task do_fetch: Succeeded
NOTE: Tasks Summary: Attempted 1181 tasks of which 1 didn't need to be rerun and 1 failed.

**Comment by jyong2** [comment]
Please update the .bb file in /home/fengying_chu/workspace/tsn/release-58/build/../intel-embedded-system-enabling/meta-virtualization/recipes-containers/lxc/lxc_4.0.1.bb, the SRC_URI changed from:
http://linuxcontainers.org/downloads/lxc-4.0.1.tar.gz
to:
http://linuxcontainers.org/downloads/lxc/lxc-4.0.1.tar.gz

LXC download was moved recently.

**Comment by fengyingchu0827** [comment]
I have changed the file lxc_4.0.1.bb and it works. Thanks.
