### ISSUE TITLE
wrong oe-init-build-env path 

### ISSUE THREAD

**Issue by jan2son** [intel/iotg-yocto-ese-manifest#4]
diff --git a/README.md b/README.md
index f81f9a0..ba2fc17 100644
--- a/README.md
+++ b/README.md
@@ -110,7 +110,7 @@ Make a branch.
 Start build process.
 
     $ cd <work_dir>/build
-    $ . ../intel-embedded-system-enabling-pre/oe-init-build-env .
+    $ . ../intel-embedded-system-enabling/oe-init-build-env .
 
 Run bitbake compilation.

**Comment by jyong2** [comment]
Thanks, updated the README file.
