### ISSUE TITLE
obsolete meta-virtualization commit

### ISSUE THREAD

**Issue by jan2son** [intel/iotg-yocto-ese-manifest#5]
1) Build Error
ERROR: mc:x86:lxc-4.0.1-r0 do_fetch: Fetcher failure for URL: 'http://linuxcontainers.org/downloads/lxc-4.0.1.tar.gz'. Unable to fetch URL from any source.

2) From "https://linuxcontainers.org/lxc/downloads/" the correct path is:
    https://linuxcontainers.org/downloads/lxc/lxc-4.0.1.tar.gz

3) So this is meta-virtualization issue. This was fixed by commit 55b5e02d

4) So why do you use commit 61f1cd9c, it is obsolete.

  <project name="meta-virtualization"
           remote="git.yoctoproject.org"
           path="intel-embedded-system-enabling/meta-virtualization"
           revision="ff997b6b3ba800978546098ab3cdaa113b6695e1" >
  </project>
5) This is good place for sarcasm: Did someone eve tried to build it? I see more errors, I am sure this fails.

Jan

**Comment by jyong2** [comment]
This is a known issue, lxc downloads was moved soon after the latest release was made.

**Comment by jan2son** [comment]
Hello, I do not want to mess your project issues... but...

> This is a known issue, lxc downloads was moved soon after the latest  
> release was made.


Nice to know, do you have some list of know issues? ...because I can  
not see it. There is really more issues in your project.
I just wonder how this happend?

I asked you colleagues for details ***@***.*** It is sad,  
no response... (yes I could be more patient but man, it is internet  
age - 21 century).

Intel representatives and support are unclear about this yocto-iotg  
project. I see effort to make it public but it is obviously heavily  
untested.
We are looking forward for public EHL support and  yocto-iotg. Could  
you please be so kind and provide us more details about this project,  
timeline and what to expect.

I do no want to debug your whole project build... especially when it  
is all known.
We would appreciate bit of cooperation. We are ready to test, spread  
across our customers. I hope this could also help you in spirit of  
opensource community.

Btw. I still can not build the yocto-iotg, no wonder... obsolete poky...
Problem here:
   ERROR: ParseError at  
/home/honza/yocto-iotg/build/../intel-embedded-system-enabling/meta-virtualization/recipes-extended/libvirt/libvirt-python.inc:1: Could not inherit file  
classes/python3targetconfig.bbclass

   ls ~/yocto-iotg/intel-embedded-system-enabling/meta/classes/python* -1
     meta/classes/python3-dir.bbclass
     meta/classes/python3native.bbclass

   git log --oneline
     b9296bdeaa (HEAD, m/master) wic: Add 512 Byte alignment to --offset
     0ff2579712 wic: Fix error message when reporting invalid offset
     62a7a10c31 wic: Fix --extra-space argument handling
     897aaff896 wic: Add --offset argument for partitions


   ***@***.***:~/yocto-iotg/intel-embedded-system-enabling/meta$ git  
checkout master
     Previous HEAD position was b9296bdeaa wic: Add 512 Byte alignment  
to --offset
     Branch 'master' set up to track remote branch 'master' from 'origin'.
     Switched to a new branch 'master'

   ***@***.***:~/yocto-iotg/intel-embedded-system-enabling/meta$ ls  
classes/python* -1
     classes/python3-dir.bbclass
     classes/python3native.bbclass
     classes/python3targetconfig.bbclass

... also known right? I would really appreciate a) fix in current  
project or b)publish know issues and solutions.


Thank you for understanding.

Best Regards,
Jan Janson
SW Engineer (yocto project)
congatec


Tel:
+420 371 121 281
Email:
***@***.***
Web:
www.congatec.com
congatec s.r.o. | Brojova 16 | 301 00 Plzen | Czech Republic
_________________
Auwiesenstraße 5
94469
Deggendorf
Deutschland
_________________
Management Board: Jason Carlson, G. Edi, J. Wenzl, T. Schultze
Place of Business: Deggendorf | HRB Deggendorf 5276

**Comment by kimhoemo** [comment]
> Hello, I do not want to mess your project issues... but...
> This is a known issue, lxc downloads was moved soon after the latest release was made.
> Nice to know, do you have some list of know issues? ...because I can not see it. There is really more issues in your project. I just wonder how this happend? I asked you colleagues for details ***@***.*** It is sad, no response... (yes I could be more patient but man, it is internet age - 21 century). Intel representatives and support are unclear about this yocto-iotg project. I see effort to make it public but it is obviously heavily untested. We are looking forward for public EHL support and yocto-iotg. Could you please be so kind and provide us more details about this project, timeline and what to expect. I do no want to debug your whole project build... especially when it is all known. We would appreciate bit of cooperation. We are ready to test, spread across our customers. I hope this could also help you in spirit of opensource community. Btw. I still can not build the yocto-iotg, no wonder... obsolete poky... Problem here: ERROR: ParseError at /home/honza/yocto-iotg/build/../intel-embedded-system-enabling/meta-virtualization/recipes-extended/libvirt/libvirt-python.inc:1: Could not inherit file classes/python3targetconfig.bbclass ls ~/yocto-iotg/intel-embedded-system-enabling/meta/classes/python* -1 meta/classes/python3-dir.bbclass meta/classes/python3native.bbclass git log --oneline b9296bdeaa (HEAD, m/master) wic: Add 512 Byte alignment to --offset 0ff2579712 wic: Fix error message when reporting invalid offset 62a7a10c31 wic: Fix --extra-space argument handling 897aaff896 wic: Add --offset argument for partitions ***@***.***:~/yocto-iotg/intel-embedded-system-enabling/meta$ git checkout master Previous HEAD position was b9296bdeaa wic: Add 512 Byte alignment to --offset Branch 'master' set up to track remote branch 'master' from 'origin'. Switched to a new branch 'master' ***@***.***:~/yocto-iotg/intel-embedded-system-enabling/meta$ ls classes/python* -1 classes/python3-dir.bbclass classes/python3native.bbclass classes/python3targetconfig.bbclass ... also known right? I would really appreciate a) fix in current project or b)publish know issues and solutions. Thank you for understanding. Best Regards, Jan Janson SW Engineer (yocto project) congatec Tel: +420 371 121 281 Email: ***@***.*** Web: [www.congatec.com](http://www.congatec.com) congatec s.r.o. | Brojova 16 | 301 00 Plzen | Czech Republic
> […](#)
> _________________ Auwiesenstraße 5 94469 Deggendorf Deutschland
> _________________ Management Board: Jason Carlson, G. Edi, J. Wenzl, T. Schultze Place of Business: Deggendorf | HRB Deggendorf 5276

Have you submitted your question via IPS?

**Comment by jan2son** [comment]
Hello,
IPS? sure, Case 00597652 for example - where we ask mainline kernel  
timeline. No response, just we do not know.
Now it gets worse when yocto iotg is not possible to build. Known  
Issues could help.

Best Regards, Jan Janson



Quoting Mok Kim Hoe ***@***.***>:

>> Hello, I do not want to mess your project issues... but...
>> This is a known issue, lxc downloads was moved soon after the  
>> latest release was made.
>> Nice to know, do you have some list of know issues? ...because I  
>> can not see it. There is really more issues in your project. I just  
>> wonder how this happend? I asked you colleagues for details  
>> ***@***.*** It is sad, no response... (yes I could be more patient  
>> but man, it is internet age - 21 century). Intel representatives  
>> and support are unclear about this yocto-iotg project. I see effort  
>> to make it public but it is obviously heavily untested. We are  
>> looking forward for public EHL support and yocto-iotg. Could you  
>> please be so kind and provide us more details about this project,  
>> timeline and what to expect. I do no want to debug your whole  
>> project build... especially when it is all known. We would  
>> appreciate bit of cooperation. We are ready to test, spread across  
>> our customers. I hope this could also help you in spirit of  
>> opensource community. Btw. I still can not build the yocto-iotg, no  
>> wonder... obsolete poky... Problem here: ERROR: ParseError at  
>> /home/honza/yocto-iotg/build/../intel-embedded-system-enabling/meta-virtualization/recipes-extended/libvirt/libvirt-python.inc:1: Could not inherit file classes/python3targetconfig.bbclass ls ~/yocto-iotg/intel-embedded-system-enabling/meta/classes/python* -1 meta/classes/python3-dir.bbclass meta/classes/python3native.bbclass git log --oneline b9296bdeaa (HEAD, m/master) wic: Add 512 Byte alignment to --offset 0ff2579712 wic: Fix error message when reporting invalid offset 62a7a10c31 wic: Fix --extra-space argument handling 897aaff896 wic: Add --offset argument for partitions ***@***.***:~/yocto-iotg/intel-embedded-system-enabling/meta$ git checkout master Previous HEAD position was b9296bdeaa wic: Add 512 Byte alignment to --offset Branch 'master' set up to track remote branch 'master' from 'origin'. Switched to a new branch 'master' ***@***.***:~/yocto-iotg/intel-embedded-system-enabling/meta$ ls classes/python* -1 classes/python3-dir.bbclass classes/python3native.bbclass classe
 s/python3targetconfig.bbclass ... also known right? I would really appreciate a) fix in current project or b)publish know issues and solutions. Thank you for understanding. Best Regards, Jan Janson SW Engineer (yocto project) congatec Tel: +420 371 121 281 Email: ***@***.*** Web: [www.congatec.com](http://www.congatec.com) congatec s.r.o. | Brojova 16 | 301 00 Plzen | Czech

**Comment by kimhoemo** [comment]
> Hello, IPS? sure, Case 00597652 for example - where we ask mainline kernel timeline. No response, just we do not know. Now it gets worse when yocto iotg is not possible to build. Known Issues could help. Best Regards, Jan Janson Quoting Mok Kim Hoe ***@***.***>:
> > Hello, I do not want to mess your project issues... but... > This is a known issue, lxc downloads was moved soon after the > latest release was made. > Nice to know, do you have some list of know issues? ...because I > can not see it. There is really more issues in your project. I just > wonder how this happend? I asked you colleagues for details > ***@***.*** It is sad, no response... (yes I could be more patient > but man, it is internet age - 21 century). Intel representatives > and support are unclear about this yocto-iotg project. I see effort > to make it public but it is obviously heavily untested. We are > looking forward for public EHL support and yocto-iotg. Could you > please be so kind and provide us more details about this project, > timeline and what to expect. I do no want to debug your whole > project build... especially when it is all known. We would > appreciate bit of cooperation. We are ready to test, spread across > our customers. I hope this could also help you in spirit of > opensource community. Btw. I still can not build the yocto-iotg, no > wonder... obsolete poky... Problem here: ERROR: ParseError at > /home/honza/yocto-iotg/build/../intel-embedded-system-enabling/meta-virtualization/recipes-extended/libvirt/libvirt-python.inc:1: Could not inherit file classes/python3targetconfig.bbclass ls ~/yocto-iotg/intel-embedded-system-enabling/meta/classes/python* -1 meta/classes/python3-dir.bbclass meta/classes/python3native.bbclass git log --oneline b9296bdeaa (HEAD, m/master) wic: Add 512 Byte alignment to --offset 0ff2579712 wic: Fix error message when reporting invalid offset 62a7a10c31 wic: Fix --extra-space argument handling 897aaff896 wic: Add --offset argument for partitions ***@***.***:~/yocto-iotg/intel-embedded-system-enabling/meta$ git checkout master Previous HEAD position was b9296bdeaa wic: Add 512 Byte alignment to --offset Branch 'master' set up to track remote branch 'master' from 'origin'. Switched to a new branch 'master' ***@***.***:~/yocto-iotg/intel-embedded-system-enabling/meta$ ls classes/python* -1 classes/python3-dir.bbclass classes/python3native.bbclass classe
> s/python3targetconfig.bbclass ... also known right? I would really appreciate a) fix in current project or b)publish know issues and solutions. Thank you for understanding. Best Regards, Jan Janson SW Engineer (yocto project) congatec Tel: +420 371 121 281 Email: ***@***.*** Web: [[www.congatec.com](http://www.congatec.com)](http://www.congatec.com%5D(http://www.congatec.com)) congatec s.r.o. | Brojova 16 | 301 00 Plzen | Czech
> […](#)
> > Republic > […](#) > _________________ Auwiesenstraße 5 94469 Deggendorf Deutschland > _________________ Management Board: Jason Carlson, G. Edi, J. > Wenzl, T. Schultze Place of Business: Deggendorf | HRB Deggendorf > 5276 Have you submitted your question via IPS? -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#5 (comment)](https://github.com/intel/iotg-yocto-ese-manifest/issues/5#issuecomment-820801781)

Hi, I have checked on the IPS ticket, it was closed. Our tech specialist has replied but I didn't see any comments from your team. We have release note and get started guide for specific platform to help user to build Yocto Project*-based image. If you have further questions regarding the build step from get started guide, please file a new IPS. Thanks

**Comment by jan2son** [comment]
Hello Mr. Hoe,
first of all thank you for open communication, I understand this is  
not what you usually do and it is very hard for us to reach right  
people on your side.
Regarding timeline and support - I fully understand your position and  
IPS approach. Sorry, but now we do support more you now than asking  
for support. We debug your work.

There are bugs in the repository not mentioned in the guides or  
release notes. You use opensource repository - github. On such  
repository is communication about bugs and cooperation expected. I  
filled two issues which shows (I can be wrong of course but I see no  
other explanation) that you did not test it AND not published known  
issues. This leads to reinventing a wheel on our side and debugging  
your work. Usually this is OK on github but your approach is  
authoritative which means all this work is odd.

Finally I found next (third issue) in your manifest (you are using  
obsolete commit again) which prevents to build it. I expected this is  
not mistake - especially when you say we know it "it is known issue".  
So I expected communication could help.

For a community could be helpful to create other issues on github - by  
me. But this shows your mistakes. I see no better way than this way.  
Debug your work, fill issues and let others to see it and benefit from  
solutions in the section...

This is really what you expect? I do not expect that.
It is about cooperation - I would expect your secret known issues as  
temporary solution because IPS will not provide something like this  
(or not soon).


Best Regards,
Jan Janson



Quoting Mok Kim Hoe ***@***.***>:

**Comment by jan2son** [comment]
Thank you. I found the issue in document ID# 619566 on page 13.
