### ISSUE TITLE
Can't find host GBE

### ISSUE THREAD

**Issue by kimjishu** [intel/iotg-yocto-ese-manifest#6]
I have EHL CRB. There are 3 Ethernet Port, 1 HOST GBE and 2 PSE GBEs.
2 PSE GBEs are avalable. But can't find HOST GBE. (I tried "ip link show", "ifconfig", "lspci -v")
How can i use HOST GBE?

**Comment by kimhoemo** [comment]
Hi, 

For product related question, please submit IPS ticket for supports.
Thanks.
