### ISSUE TITLE
Three tasks compiling took me a day but not over. 

### ISSUE THREAD

**Issue by GinoChen1218** [intel/iotg-yocto-ese-manifest#7]
Initialising tasks: 100% |######################################################################################################################################| Time: 0:01:12
Sstate summary: Wanted 3004 Found 0 Missed 3004 Current 1223 (0% match, 28% complete)
NOTE: Executing Tasks
Currently  4 running tasks (4901 of 11806)  41% |###################################################                                                                          |
0: mc:x86-rt:clang-native-10.0.1-r0 do_compile (pid 5091)   0% |                                                                                                              |
1: mc:x86-rt:linux-intel-ese-lts-rt-5.4-5.4++gitAUTOINC+8b7b8b8190_e00ce2dbe2-r0 do_compile_kernelmodules - 24h39m56s (pid 5135)
2: mc:x86-rt:protobuf-3.11.4-r0 do_compile - 24h39m54s (pid 5214)
3: mc:x86-rt:linux-intel-ese-lts-5.4-5.4++gitAUTOINC+8b7b8b8190_698dc049f6-r0 do_compile - 24h39m54s (pid 5202)

Hello
Three tasks compiling took me a day but not over. 
Do I need to re-execute it?

**Comment by minilanl** [comment]
did you success at last?i meet other questions
